### ISSUE TITLE
Deployment Agent refactoring - todos

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-deployment-agent#75]
- [ ] If stacks are not yet present, they are created
- [x] (If update of stack fails, give option to forcefully delete and create)
- [x] config
   - [x] {ONE BRANCH OPS:} docker-stack-recipe becomes list
   - [x] docker-stack-recipe has "depends_on" member where same tag in dependency repo is assumed
          - On which level is this logic situated? Currently, the top level is only aware of "changes". If there are changes, the entire stack is redeployed. The nature or kind of the changes does not matter, but is passed to the notification. One could parse the version and introduce it explicitly.
   - [x] {ONE BRANCH OPS:} command for ops: for every services folder, create per-deployment stack file (assume `up-DEPLOYMENT`)
   - [x] {ONE BRANCH OPS:} move stack-name from portainer-obj to docker-stack-recipe
- [ ] dockerhub images are checked out not by `latest` but by explicit version tag 

Changes in github-watcher-config:
- branch --> branches: Regex for extracting versions
- tag: Regex for extracting versions

Changes in dockerhub-watcher:
- imagenames: Regex for extracting the version from the imagename

Polled entities:
- Dockerhub
- Simcore
- Ops-Stack
- Ops-Config

**Comment by mrnicegyu11** [comment]
re: dockerhub images: They are not specified in the deployment-agent, but in the stack file. They come from the `DOCKER_IMAGE_TAG` variable set in the env-vars of the deployment agent (needs refactoring!)

**Comment by GitHK** [comment]
Also, please take note that the dynamic-sidecar has to use the same image, which is specified in one of the env vars on the director-v2.

```yaml
- DYNAMIC_SIDECAR_IMAGE=${DOCKER_REGISTRY:-itisfoundation}/dynamic-sidecar:${DOCKER_IMAGE_TAG:-latest}
```

**Comment by mrnicegyu11** [comment]
Changes:
- Every watched entity identifies with (semantic) versions.
  - Ops-Repo: One Branch for all deployments, Branch per Version (acc to google SRE guidelines)
  - Ops-Config: Tag per Version, Branch per Deployment
  - Simcore: Tag per Version
  - Dockerhub: Version parsed form Image-Name with prefix
- Versions of all entities are polled periodically
- Target Version is given as env-var of the deployment agent
- Semantic versions are synced, letter additions (1.2.3a) are applied immedeatly
- Before a push the desired state is compared with the current state (GET/PUT via portainer). If a change occurs, a notification is sent
